In [1]:
%pip install pandas
%pip install matplotlib
%pip install "numpy<2.0.0"
%pip install scikit-learn
%pip install --upgrade matplotlib


Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("./house-prices.csv")
df


Home   Price  SqFt
0       1  114300  1790
1       2  114200  2030
2       3  114800  1740
3       4   94700  1980
4       5  119800  2130
..    ...     ...   ...
123   124  119700  1900
124   125  147900  2160
125   126  113500  2070
126   127  149900  2020
127   128  124600  2250

[128 rows x 3 columns]

In [4]:
reg = linear_model.LinearRegression()
reg.fit(df[['SqFt']],df.Price)

LinearRegression()

In [5]:
reg.predict([[5000]])

C:\Users\DINESH P SUTHAR\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([341040.4613053])

In [6]:
reg.coef_

array([70.22631824])

In [7]:
reg.intercept_

-10091.129909123149

In [8]:
70.22631824*5000+-10091.129909123149

341040.46129087685

In [9]:
import pickle

In [11]:
with open('model_pickle','wb') as f:
    pickle.dump(reg,f)

In [12]:
with open('model_pickle','rb') as f:
    mp = pickle.load(f)

In [14]:
mp.predict([[5000]])

C:\Users\DINESH P SUTHAR\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([341040.4613053])

In [15]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\DINESH P SUTHAR\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\externals\__init__.py)

In [16]:
import joblib


In [19]:
%pip install joblib


Note: you may need to restart the kernel to use updated packages.


In [21]:
joblib.dump(reg,'model_joblib')

['model_joblib']

In [22]:
mj = joblib.load('model_joblib')


In [23]:
mj.predict([[5000]])

C:\Users\DINESH P SUTHAR\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([341040.4613053])

In [24]:
mj.coef_

array([70.22631824])

In [25]:
mj.intercept_


-10091.129909123149